using System.Text.Json.Serialization; using Microsoft.AspNetCore.Diagnostics.HealthChecks; using Microsoft.AspNetCore.RateLimiting; using Microsoft.EntityFrameworkCore; using Microsoft.OpenApi.Models; using NuamExchange.Api.Errors; using NuamExchange.Api.Middleware; using NuamExchange.Application.Classifications; using NuamExchange.Infrastructure; using NuamExchange.Infrastructure.Persistence;
var builder=WebApplication.CreateBuilder(args); if(!builder.Environment.IsDevelopment()&&!builder.Environment.IsEnvironment("Testing")) throw new InvalidOperationException("La autenticación real todavía no está implementada. El backend solo puede ejecutarse en Development o Testing hasta completar el Prompt 011.");
builder.Services.AddProblemDetails(); builder.Services.AddExceptionHandler<GlobalExceptionHandler>(); builder.Services.AddScoped<IClassificationService,ClassificationService>(); builder.Services.AddInfrastructure(builder.Configuration); builder.Services.AddControllers().AddJsonOptions(o=>{o.JsonSerializerOptions.PropertyNamingPolicy=System.Text.Json.JsonNamingPolicy.CamelCase;o.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());o.JsonSerializerOptions.DefaultIgnoreCondition=JsonIgnoreCondition.WhenWritingNull;});
builder.Services.AddCors(o=>o.AddPolicy("Frontend",p=>p.WithOrigins(builder.Configuration.GetSection("Cors:FrontendOrigins").Get<string[]>()??[]).WithMethods("GET","POST","PUT","PATCH","DELETE","OPTIONS").WithHeaders("Content-Type","Authorization","If-Match","x-correlation-id").WithExposedHeaders("ETag","x-correlation-id")));
builder.Services.AddRateLimiter(o=>{o.RejectionStatusCode=StatusCodes.Status429TooManyRequests;o.AddFixedWindowLimiter("General",l=>{l.PermitLimit=100;l.Window=TimeSpan.FromMinutes(1);l.QueueLimit=0;});});
builder.Services.AddHealthChecks().AddCheck("self",()=>Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckResult.Healthy()).AddDbContextCheck<NuamExchangeDbContext>("sqlserver");
builder.Services.AddEndpointsApiExplorer(); builder.Services.AddSwaggerGen(c=>{c.SwaggerDoc("v1",new OpenApiInfo{Title="NUAM Exchange API",Version="v1",Description="Implementación inicial. Autenticación pendiente de implementación."});c.AddSecurityDefinition("Bearer",new OpenApiSecurityScheme{Description="JWT Bearer provisional para Prompt 011. Autenticación pendiente de implementación.",Name="Authorization",In=ParameterLocation.Header,Type=SecuritySchemeType.Http,Scheme="bearer",BearerFormat="JWT"});});
var app=builder.Build(); if(app.Configuration.GetValue<bool>("Database:ApplyMigrationsOnStartup")){if(!app.Environment.IsDevelopment())throw new InvalidOperationException("Las migraciones automáticas solo están permitidas en Development.");using var scope=app.Services.CreateScope();await scope.ServiceProvider.GetRequiredService<NuamExchangeDbContext>().Database.MigrateAsync();}
app.UseExceptionHandler(); app.UseMiddleware<CorrelationIdMiddleware>(); app.UseMiddleware<RequestLoggingMiddleware>(); if(app.Environment.IsDevelopment()){app.UseSwagger();app.UseSwaggerUI();} app.UseHttpsRedirection(); app.UseCors("Frontend"); app.UseRateLimiter(); app.MapControllers().RequireRateLimiting("General"); app.MapHealthChecks("/health/live",new HealthCheckOptions{Predicate=r=>r.Name=="self"}); app.MapHealthChecks("/health/ready",new HealthCheckOptions{Predicate=r=>r.Name=="sqlserver"}); app.Run();
public partial class Program { }
