// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NuamExchange.Infrastructure.Persistence;

#nullable disable

namespace NuamExchange.Infrastructure.Migrations
{
    [DbContext(typeof(NuamExchangeDbContext))]
    [Migration("20260624021135_AddIdentityFoundation")]
    partial class AddIdentityFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NuamExchange.Domain.Classifications.Classification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventSequence")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UpdateFactor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYear");

                    b.HasIndex("Market");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("Status");

                    b.HasIndex("FiscalYear", "Market", "Instrument", "PaymentDate", "EventSequence")
                        .IsUnique();

                    b.ToTable("Classifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "CAL-2024-001",
                            Amount = 1250000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Dividendo provisorio acciones serie A",
                            EventSequence = "EVT-ACC-001",
                            FiscalYear = 2024,
                            Instrument = "NUAM-A",
                            Market = "Acciones",
                            PaymentDate = new DateOnly(2024, 1, 15),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Vigente",
                            UpdateFactor = 1.002345m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2024-002",
                            Amount = 8425000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Interés bono corporativo febrero",
                            EventSequence = "EVT-RF-014",
                            FiscalYear = 2024,
                            Instrument = "BNUAM-24",
                            Market = "Renta Fija",
                            PaymentDate = new DateOnly(2024, 2, 28),
                            RowVersion = new byte[0],
                            Source = "Carga X Factor",
                            Status = "Pendiente",
                            UpdateFactor = 0.998761m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2024-003",
                            Amount = 2378000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rescate fondo liquidez local",
                            EventSequence = "EVT-FON-009",
                            FiscalYear = 2024,
                            Instrument = "FONDO-LIQ",
                            Market = "Fondos",
                            PaymentDate = new DateOnly(2024, 3, 12),
                            RowVersion = new byte[0],
                            Source = "Carga X Monto",
                            Status = "Observada",
                            UpdateFactor = 1.010102m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2024-004",
                            Amount = 980000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Distribución anual de utilidades",
                            EventSequence = "EVT-ACC-019",
                            FiscalYear = 2024,
                            Instrument = "ANDES-B",
                            Market = "Acciones",
                            PaymentDate = new DateOnly(2024, 4, 30),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Rechazada",
                            UpdateFactor = 1.000001m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2024-005",
                            Amount = 11540000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Amortización parcial instrumento reajustable",
                            EventSequence = "EVT-RF-022",
                            FiscalYear = 2024,
                            Instrument = "BCORP-27",
                            Market = "Renta Fija",
                            PaymentDate = new DateOnly(2024, 5, 18),
                            RowVersion = new byte[0],
                            Source = "Carga X Monto",
                            Status = "Vigente",
                            UpdateFactor = 1.034568m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2024-006",
                            Amount = 3210000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Distribución fondo crecimiento",
                            EventSequence = "EVT-FON-017",
                            FiscalYear = 2024,
                            Instrument = "FONDO-CREC",
                            Market = "Fondos",
                            PaymentDate = new DateOnly(2024, 6, 21),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Pendiente",
                            UpdateFactor = 1.012m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2025-001",
                            Amount = 4567000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Dividendo adicional serie C",
                            EventSequence = "EVT-ACC-031",
                            FiscalYear = 2025,
                            Instrument = "PACIFICO-C",
                            Market = "Acciones",
                            PaymentDate = new DateOnly(2025, 1, 10),
                            RowVersion = new byte[0],
                            Source = "Carga X Factor",
                            Status = "Vigente",
                            UpdateFactor = 1.045678m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2025-002",
                            Amount = 18450000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cupón semestral tesorería local",
                            EventSequence = "EVT-RF-034",
                            FiscalYear = 2025,
                            Instrument = "TES-CLP-25",
                            Market = "Renta Fija",
                            PaymentDate = new DateOnly(2025, 2, 14),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Observada",
                            UpdateFactor = 1.007654m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2025-003",
                            Amount = 7650000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pago beneficio fondo infraestructura",
                            EventSequence = "EVT-FON-028",
                            FiscalYear = 2025,
                            Instrument = "FONDO-INFRA",
                            Market = "Fondos",
                            PaymentDate = new DateOnly(2025, 3, 19),
                            RowVersion = new byte[0],
                            Source = "Carga X Monto",
                            Status = "Pendiente",
                            UpdateFactor = 0.995432m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2025-004",
                            Amount = 2143000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Evento societario de caja",
                            EventSequence = "EVT-ACC-044",
                            FiscalYear = 2025,
                            Instrument = "CORDILLERA-A",
                            Market = "Acciones",
                            PaymentDate = new DateOnly(2025, 4, 23),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Vigente",
                            UpdateFactor = 1.000456m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2025-005",
                            Amount = 9350000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Interés instrumento bancario",
                            EventSequence = "EVT-RF-041",
                            FiscalYear = 2025,
                            Instrument = "BANC-30",
                            Market = "Renta Fija",
                            PaymentDate = new DateOnly(2025, 5, 7),
                            RowVersion = new byte[0],
                            Source = "Carga X Factor",
                            Status = "Rechazada",
                            UpdateFactor = 1.023001m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2025-006",
                            Amount = 5289000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Distribución extraordinaria fondo valor",
                            EventSequence = "EVT-FON-033",
                            FiscalYear = 2025,
                            Instrument = "FONDO-VALOR",
                            Market = "Fondos",
                            PaymentDate = new DateOnly(2025, 6, 16),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Vigente",
                            UpdateFactor = 1.01789m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2025-007",
                            Amount = 1599000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pago evento especial acciones",
                            EventSequence = "EVT-ACC-052",
                            FiscalYear = 2025,
                            Instrument = "NORTE-D",
                            Market = "Acciones",
                            PaymentDate = new DateOnly(2025, 7, 22),
                            RowVersion = new byte[0],
                            Source = "Carga X Monto",
                            Status = "Pendiente",
                            UpdateFactor = 1.008m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2025-008",
                            Amount = 13200000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Liquidación cupón deuda local",
                            EventSequence = "EVT-RF-058",
                            FiscalYear = 2025,
                            Instrument = "DEUDA-LOCAL",
                            Market = "Renta Fija",
                            PaymentDate = new DateOnly(2025, 8, 11),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Observada",
                            UpdateFactor = 0.991234m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2026-001",
                            Amount = 4490000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Distribución fondo balanceado",
                            EventSequence = "EVT-FON-061",
                            FiscalYear = 2026,
                            Instrument = "FONDO-BAL",
                            Market = "Fondos",
                            PaymentDate = new DateOnly(2026, 1, 9),
                            RowVersion = new byte[0],
                            Source = "Carga X Factor",
                            Status = "Vigente",
                            UpdateFactor = 1.006789m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2026-002",
                            Amount = 6780000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Dividendo mínimo obligatorio",
                            EventSequence = "EVT-ACC-067",
                            FiscalYear = 2026,
                            Instrument = "SUR-A",
                            Market = "Acciones",
                            PaymentDate = new DateOnly(2026, 2, 27),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Pendiente",
                            UpdateFactor = 1.011111m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2026-003",
                            Amount = 22100000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Pago cupón bono temático",
                            EventSequence = "EVT-RF-071",
                            FiscalYear = 2026,
                            Instrument = "BONO-VERDE",
                            Market = "Renta Fija",
                            PaymentDate = new DateOnly(2026, 3, 13),
                            RowVersion = new byte[0],
                            Source = "Carga X Monto",
                            Status = "Vigente",
                            UpdateFactor = 1.029999m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2026-004",
                            Amount = 3890000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rescate programado fondo tecnología",
                            EventSequence = "EVT-FON-074",
                            FiscalYear = 2026,
                            Instrument = "FONDO-TEC",
                            Market = "Fondos",
                            PaymentDate = new DateOnly(2026, 4, 24),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Rechazada",
                            UpdateFactor = 1.00321m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2026-005",
                            Amount = 2785000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Distribución complementaria",
                            EventSequence = "EVT-ACC-080",
                            FiscalYear = 2026,
                            Instrument = "OESTE-B",
                            Market = "Acciones",
                            PaymentDate = new DateOnly(2026, 5, 15),
                            RowVersion = new byte[0],
                            Source = "Carga X Factor",
                            Status = "Observada",
                            UpdateFactor = 1.019876m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2026-006",
                            Amount = 16750000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Vencimiento letra corporativa",
                            EventSequence = "EVT-RF-083",
                            FiscalYear = 2026,
                            Instrument = "LETRA-26",
                            Market = "Renta Fija",
                            PaymentDate = new DateOnly(2026, 6, 18),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Pendiente",
                            UpdateFactor = 1.000999m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2026-007",
                            Amount = 8123000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Distribución fondo internacional",
                            EventSequence = "EVT-FON-088",
                            FiscalYear = 2026,
                            Instrument = "FONDO-USD",
                            Market = "Fondos",
                            PaymentDate = new DateOnly(2026, 7, 30),
                            RowVersion = new byte[0],
                            Source = "Carga X Monto",
                            Status = "Vigente",
                            UpdateFactor = 0.987654m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "CAL-2026-008",
                            Amount = 3310000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Evento de capital con pago asociado",
                            EventSequence = "EVT-ACC-095",
                            FiscalYear = 2026,
                            Instrument = "CENTRO-E",
                            Market = "Acciones",
                            PaymentDate = new DateOnly(2026, 8, 20),
                            RowVersion = new byte[0],
                            Source = "Manual",
                            Status = "Observada",
                            UpdateFactor = 1.015555m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("NuamExchange.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NuamExchange.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NuamExchange.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NuamExchange.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NuamExchange.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
