using System.Security.Cryptography; using System.Text.RegularExpressions; using NuamExchange.Application.Common; using NuamExchange.Application.Exceptions; using NuamExchange.Domain.Classifications;
namespace NuamExchange.Application.Classifications;
public interface IClassificationService{Task<PaginatedResponse<ClassificationDto>> ListAsync(ClassificationListRequest r,CancellationToken ct);Task<ClassificationCatalogsDto> GetCatalogsAsync(CancellationToken ct);Task<ClassificationDto> GetByIdAsync(string id,CancellationToken ct);Task<ClassificationWriteResponse> CreateAsync(CreateClassificationRequest r,CancellationToken ct);Task<ClassificationWriteResponse> UpdateAsync(string id,UpdateClassificationRequest r,string? ifMatch,CancellationToken ct);Task<ClassificationWriteResponse> CopyAsync(string id,CopyClassificationRequest r,CancellationToken ct);Task DeleteAsync(string id,string? ifMatch,CancellationToken ct);}
public sealed class ClassificationService(IClassificationRepository repo) : IClassificationService
{ static readonly string[] Markets=["Acciones","Renta Fija","Fondos"]; static readonly string[] Sources=["Manual","Carga X Factor","Carga X Monto"]; static readonly string[] Sorts=["fiscalYear","instrument","paymentDate","amount","status"];
 public async Task<PaginatedResponse<ClassificationDto>> ListAsync(ClassificationListRequest r,CancellationToken ct){ValidateList(r);var items=(await repo.ListAsync(r,ct)).Select(ClassificationMapper.ToDto).ToList();var total=await repo.CountAsync(r,ct);return new(items,r.Page,r.PageSize,total,total==0?0:(int)Math.Ceiling((double)total/r.PageSize));}
 public async Task<ClassificationCatalogsDto> GetCatalogsAsync(CancellationToken ct){var c=await repo.GetCatalogsAsync(ct);var years=c.FiscalYears.Count==0?[DateTimeOffset.UtcNow.Year]:c.FiscalYears;return new(Markets,Sources,years,Enum.GetValues<ClassificationStatus>());}
 public async Task<ClassificationDto> GetByIdAsync(string id,CancellationToken ct)=>ClassificationMapper.ToDto(await Find(id,false,ct));
 public async Task<ClassificationWriteResponse> CreateAsync(CreateClassificationRequest r,CancellationToken ct){ValidateWrite(r);await EnsureNoDuplicate(r.FiscalYear,r.Market,r.Instrument,r.PaymentDate,r.EventSequence,null,ct);var now=DateTimeOffset.UtcNow;var e=new Classification(NewId(r.FiscalYear),r.Market,r.Source,r.FiscalYear,r.Instrument,r.PaymentDate,r.Description,r.EventSequence,r.UpdateFactor,r.Amount,r.Status,now,now);await repo.AddAsync(e,ct);await repo.SaveChangesAsync(ct);return new(ClassificationMapper.ToDto(e),"Calificación creada correctamente.");}
 public async Task<ClassificationWriteResponse> UpdateAsync(string id,UpdateClassificationRequest r,string? ifMatch,CancellationToken ct){ValidateWrite(r);var e=await Find(id,true,ct);var rv=ParseIfMatch(ifMatch);if(rv is not null && !e.RowVersion.SequenceEqual(rv))throw new ConcurrencyException("La calificación fue modificada por otro proceso.");await EnsureNoDuplicate(r.FiscalYear,r.Market,r.Instrument,r.PaymentDate,r.EventSequence,id,ct);e.Update(r.Market,r.Source,r.FiscalYear,r.Instrument,r.PaymentDate,r.Description,r.EventSequence,r.UpdateFactor,r.Amount,r.Status,DateTimeOffset.UtcNow);repo.Update(e,rv);await repo.SaveChangesAsync(ct);return new(ClassificationMapper.ToDto(e),"Calificación actualizada correctamente.");}
 public async Task<ClassificationWriteResponse> CopyAsync(string id,CopyClassificationRequest r,CancellationToken ct){var o=await Find(id,false,ct);var date=r.PaymentDate??o.PaymentDate;var desc=string.IsNullOrWhiteSpace(r.Description)?o.Description:r.Description;var seq=string.IsNullOrWhiteSpace(r.EventSequence)?o.EventSequence:r.EventSequence;var req=new CreateClassificationRequest(o.Market,o.Source,o.FiscalYear,o.Instrument,date,desc,seq,o.UpdateFactor,o.Amount,o.Status);ValidateWrite(req);await EnsureNoDuplicate(req.FiscalYear,req.Market,req.Instrument,req.PaymentDate,req.EventSequence,null,ct);var now=DateTimeOffset.UtcNow;var e=new Classification(NewId(req.FiscalYear),req.Market,req.Source,req.FiscalYear,req.Instrument,req.PaymentDate,req.Description,req.EventSequence,req.UpdateFactor,req.Amount,req.Status,now,now);await repo.AddAsync(e,ct);await repo.SaveChangesAsync(ct);return new(ClassificationMapper.ToDto(e),"Calificación copiada correctamente.");}
 public async Task DeleteAsync(string id,string? ifMatch,CancellationToken ct){var e=await Find(id,true,ct);var rv=ParseIfMatch(ifMatch);if(rv is not null && !e.RowVersion.SequenceEqual(rv))throw new ConcurrencyException("La calificación fue modificada por otro proceso.");repo.Remove(e,rv);await repo.SaveChangesAsync(ct);} 
 static string NewId(int year)=>$"CAL-{year}-{RandomNumberGenerator.GetHexString(8).ToUpperInvariant()}"; static byte[]? ParseIfMatch(string? v){if(string.IsNullOrWhiteSpace(v))return null;var s=v.Trim().Trim('"');try{return Convert.FromBase64String(s);}catch(FormatException){throw new ValidationException("If-Match inválido.",new Dictionary<string,string[]>{{"If-Match",["El encabezado If-Match debe contener RowVersion en Base64."]}});}}
 async Task<Classification> Find(string id,bool tracking,CancellationToken ct)=>await repo.GetByIdAsync(id,tracking,ct)??throw new NotFoundException("La calificación solicitada no existe."); async Task EnsureNoDuplicate(int y,string m,string i,DateOnly d,string e,string? ex,CancellationToken ct){if(await repo.ExistsDuplicateAsync(y,m,i,d,e,ex,ct))throw new ConflictException("Ya existe una calificación con la misma combinación de ejercicio, mercado, instrumento, fecha de pago y secuencia.");}
 static void ValidateList(ClassificationListRequest r){var er=new Dictionary<string,string[]>(); if(r.Page<1)er["page"]=["La página debe ser mayor o igual a 1."]; if(!new[]{5,10,20}.Contains(r.PageSize))er["pageSize"]=["El tamaño de página permitido es 5, 10 o 20."]; if(!Sorts.Contains(r.SortBy))er["sortBy"]=["El campo de ordenamiento no es válido."]; if(r.SortDirection is not ("asc" or "desc"))er["sortDirection"]=["La dirección debe ser asc o desc."]; if(er.Count>0)throw new ValidationException("La solicitud contiene errores de validación.",er);}
 static void ValidateWrite(CreateClassificationRequest r)=>Validate(r.Market,r.Source,r.FiscalYear,r.Instrument,r.PaymentDate,r.Description,r.EventSequence,r.UpdateFactor,r.Amount,r.Status); static void ValidateWrite(UpdateClassificationRequest r)=>Validate(r.Market,r.Source,r.FiscalYear,r.Instrument,r.PaymentDate,r.Description,r.EventSequence,r.UpdateFactor,r.Amount,r.Status);
 static void Validate(string m,string s,int y,string i,DateOnly _,string d,string e,decimal f,decimal a,ClassificationStatus st){var er=new Dictionary<string,string[]>(); if(!Markets.Contains(m))er["market"]=["El mercado no es válido."]; if(!Sources.Contains(s))er["source"]=["El origen no es válido."]; if(y<2024||y>2100)er["fiscalYear"]=["El ejercicio debe estar entre 2024 y 2100."]; if(string.IsNullOrWhiteSpace(i)||i.Length<2||i.Length>30)er["instrument"]=["El instrumento debe tener entre 2 y 30 caracteres."]; if(string.IsNullOrWhiteSpace(d)||d.Length<3||d.Length>500)er["description"]=["La descripción debe tener entre 3 y 500 caracteres."]; if(string.IsNullOrWhiteSpace(e)||e.Length<3||e.Length>30||!Regex.IsMatch(e,"^[A-Za-z0-9-]+$"))er["eventSequence"]=["La secuencia debe tener entre 3 y 30 caracteres y solo letras, números o guion."]; if(f<=0||decimal.Scale(f)>6)er["updateFactor"]=["El factor debe ser mayor que cero y tener máximo 6 decimales."]; if(a<0||decimal.Scale(a)>2)er["amount"]=["El monto debe ser mayor o igual a cero y tener máximo 2 decimales."]; if(!Enum.IsDefined(st))er["status"]=["El estado no es válido."]; if(er.Count>0)throw new ValidationException("La solicitud contiene errores de validación.",er);}
}
